AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-nodejs12.x

  Sample SAM Template for lambda-nodejs12.x
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  AthenaTesterFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: athena-test/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Policies:
      - AmazonAthenaFullAccess
      - AmazonS3FullAccess
      Events:
        AthenaTester:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /athena-tester
            Method: get
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  AthenaTesterApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/athena-tester/"
  AthenaTesterFunction:
    Description: "Athena Tester Lambda Function ARN"
    Value: !GetAtt AthenaTesterFunction.Arn
  AthenaTesterFunctionIamRole:
    Description: "Implicit IAM Role created for Athena Tester function"
    Value: !GetAtt AthenaTesterFunctionRole.Arn
